In [2]:
name= " Sachin. "
name.strip()

'Sachin.'

In [9]:
# print(name.strip())
ans= 10/0

ZeroDivisionError: division by zero

In [3]:

ans= 10/2
print(ans)
if isinstance(ans, list):
    print("This is a list")
raise ValueError("This is a float number")

5.0

ValueError: This is a float number

In [22]:
#ans= 10/2
ans= "Sachin"

In [23]:
ans=int(ans)

ValueError: invalid literal for int() with base 10: 'Sachin'

In [21]:
ans

5

In [1]:
from pydantic import BaseModel, EmailStr, Field
from typing import Optional

In [2]:

class Student(BaseModel):

    name: str = 'sachin'
    age: Optional[int] = None
    email: EmailStr
    cgpa: float = Field(gt=0, lt=10, default=5, description='A decimal value representing the cgpa of the student')

In [5]:
new_student = {'age':32, 'email':'abc@gmail.com'}


student = Student(**new_student)

print(student)
print(type(student))

name='sachin' age=32 email='abc@gmail.com' cgpa=5
<class '__main__.Student'>

In [ ]:
student_dict = dict(student)

# print(type(student_dict))

# print(student_dict['age'])

# student_json = student.model_dump_json()

# print(student_json)

# print(type(student_json))

## request library use

In [7]:
import requests
response = requests.get("https://google.com", timeout=3)
print(response.status_code)

200

In [1]:
import os
BACKEND_URL= os.environ.get("BACKEND_URL")

In [2]:
BACKEND_URL

In [7]:
if isinstance(1, int):
    print("This is a list")

This is a list

In [1]:
l=[1,2,3,4,5]

In [2]:
for i in l:
    if i%2==0:
        print(f"{i} is even")

2 is even
4 is even

In [3]:
print([i for i in l if i%2==0])

[2, 4]

In [ ]:
 c for c in clients if not search_query or search_query in c.get("name", "").lower()

In [ ]:
[c for c in clients if not search_query or search_query in c.get("name", "").lower()]

In [7]:
import pandas as pd

In [ ]:
clients = [
    {"name": "Alice", "active": True},
    {"name": "Bob", "active": False},
    {"name": "Charlie", "active": True},
]

In [9]:
df = pd.DataFrame(clients)

In [10]:
df

      name  active
0    Alice    True
1      Bob   False
2  Charlie    True

In [11]:
df = df.rename(columns={
                "name": "Full Name",
                "active": "Is Active",
            })

In [12]:
df

  Full Name  Is Active
0     Alice       True
1       Bob      False
2   Charlie       True

In [5]:
[c for c in clients if c.get("name", "").lower() == "alice"]

[{'name': 'Alice', 'active': True}]

In [19]:
if 0:
    print("hi")